import Foundation

// Canonical Asset Registry: the bundled, always-available baseline of known assets and their
// verified market mappings (docs/DEVELOPMENT.md → Canonical Asset Registry).
//
//   bundled snapshot (Resources/CanonicalAssetRegistry.json, never regenerated by the app)
//   + curated overlay (verified corrections shipped in code, e.g. Bybit TELUSDT)
//   + optional cached remote overlay (rare, validated; see RegistryOverlayStore)
//
// Ledgers keep their own asset ids (`cg:<coingecko id>`, catalog overrides like `cg:telcoin`);
// the registry is looked up from them and never changes stored data.

/// One registry record. Every field but id/symbol/name is optional so older or partial
/// snapshots and future enrichment decode without breaking.
public struct RegistryAsset: Codable, Hashable, Sendable {
    public var id: String                       // registry id, e.g. "cmc-1"
    public var symbol: String
    public var name: String
    public var coingeckoId: String?
    public var marketCapRank: Int?
    public var binanceSymbol: String?
    public var bybitSymbol: String?
    /// Other venues, keyed by source id (e.g. "gateio": "BTC_USDT", "kucoin": "BTC-USDT").
    public var exchangeSymbols: [String: String]
    /// Contract per chain, keyed by CoinGecko platform id (e.g. "ethereum", "binance-smart-chain").
    public var contracts: [String: String]
    public var stablecoin: StablecoinInfo?

    public struct StablecoinInfo: Codable, Hashable, Sendable {
        public var pegCurrency: String
        public var targetPeg: Decimal
        public init(pegCurrency: String, targetPeg: Decimal) { self.pegCurrency = pegCurrency; self.targetPeg = targetPeg }
    }

    public init(id: String, symbol: String, name: String, coingeckoId: String? = nil, marketCapRank: Int? = nil,
                binanceSymbol: String? = nil, bybitSymbol: String? = nil, exchangeSymbols: [String: String] = [:],
                contracts: [String: String] = [:], stablecoin: StablecoinInfo? = nil) {
        self.id = id; self.symbol = symbol; self.name = name; self.coingeckoId = coingeckoId; self.marketCapRank = marketCapRank
        self.binanceSymbol = binanceSymbol; self.bybitSymbol = bybitSymbol; self.exchangeSymbols = exchangeSymbols
        self.contracts = contracts; self.stablecoin = stablecoin
    }

    enum CodingKeys: String, CodingKey {
        case id, symbol, name, coingeckoId, marketCapRank, binanceSymbol, bybitSymbol, exchangeSymbols, contracts, stablecoin
    }

    public init(from d: Decoder) throws {
        let c = try d.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        symbol = try c.decode(String.self, forKey: .symbol).uppercased()
        name = try c.decode(String.self, forKey: .name)
        coingeckoId = try c.decodeIfPresent(String.self, forKey: .coingeckoId).flatMap { $0.isEmpty ? nil : $0 }
        marketCapRank = try c.decodeIfPresent(Int.self, forKey: .marketCapRank)
        binanceSymbol = try c.decodeIfPresent(String.self, forKey: .binanceSymbol).flatMap { $0.isEmpty ? nil : $0.uppercased() }
        bybitSymbol = try c.decodeIfPresent(String.self, forKey: .bybitSymbol).flatMap { $0.isEmpty ? nil : $0.uppercased() }
        exchangeSymbols = try c.decodeIfPresent([String: String].self, forKey: .exchangeSymbols) ?? [:]
        contracts = try c.decodeIfPresent([String: String].self, forKey: .contracts) ?? [:]
        stablecoin = try c.decodeIfPresent(StablecoinInfo.self, forKey: .stablecoin)
    }
}

/// The snapshot file.
public struct RegistrySnapshot: Codable, Sendable {
    public var registryVersion: String
    public var source: String?
    public var sourceRanking: String?
    public var assetCount: Int?
    public var assets: [RegistryAsset]
    public init(registryVersion: String, source: String? = nil, sourceRanking: String? = nil, assetCount: Int? = nil, assets: [RegistryAsset]) {
        self.registryVersion = registryVersion; self.source = source; self.sourceRanking = sourceRanking; self.assetCount = assetCount; self.assets = assets
    }
}

/// Changes on top of the bundled snapshot: field patches for existing ids and added assets.
/// Validated before use; an invalid overlay is ignored and the baseline stays.
public struct RegistryOverlay: Codable, Equatable, Sendable {
    public struct Patch: Codable, Equatable, Sendable {
        public var id: String
        public var binanceSymbol: String?
        public var bybitSymbol: String?
        public var exchangeSymbols: [String: String]?
        public var contracts: [String: String]?          // merged into the asset's contracts
        public var stablecoin: RegistryAsset.StablecoinInfo?
        public init(id: String, binanceSymbol: String? = nil, bybitSymbol: String? = nil, exchangeSymbols: [String: String]? = nil,
                    contracts: [String: String]? = nil, stablecoin: RegistryAsset.StablecoinInfo? = nil) {
            self.id = id; self.binanceSymbol = binanceSymbol; self.bybitSymbol = bybitSymbol; self.exchangeSymbols = exchangeSymbols
            self.contracts = contracts; self.stablecoin = stablecoin
        }
    }
    public var overlayVersion: String
    /// Snapshot versions this overlay applies to; nil = any.
    public var baseRegistryVersions: [String]?
    public var patches: [Patch]
    public var added: [RegistryAsset]?
    public init(overlayVersion: String, baseRegistryVersions: [String]? = nil, patches: [Patch], added: [RegistryAsset]? = nil) {
        self.overlayVersion = overlayVersion; self.baseRegistryVersions = baseRegistryVersions; self.patches = patches; self.added = added
    }

    /// Verified corrections shipped with the app.
    /// - TEL: Bybit spot TELUSDT (checked 2026-09-30: /v5/market/instruments-info → TEL/USDT, Trading).
    ///   CoinGecko `telcoin-2` lists one contract on Ethereum, Base and Polygon (same address).
    /// - KAS: Bybit spot KASUSDT (checked 2026-09-30: instruments-info → KAS/USDT, Trading, and
    ///   CoinGecko /coins/kaspa/tickers lists Bybit KAS/USDT for this coin id). Not on Binance and
    ///   no contracts, so without this CoinGecko was its only source.
    public static let curated = RegistryOverlay(overlayVersion: "curated-2026-09-30", patches: [
        Patch(id: "cmc-2394", bybitSymbol: "TELUSDT",
              contracts: ["base": "0x7e13b43065380acdec1c2d138c579cbbbafa0731", "polygon-pos": "0x7e13b43065380acdec1c2d138c579cbbbafa0731"]),
        Patch(id: "cmc-20396", bybitSymbol: "KASUSDT"),
    ])

    public enum ValidationError: Error, Equatable { case wrongBase(String), unknownID(String), duplicateID(String), empty }

    /// Structural checks against a snapshot. Nothing is applied by this function.
    public func validate(against s: RegistrySnapshot) throws {
        if patches.isEmpty && (added ?? []).isEmpty { throw ValidationError.empty }
        if let b = baseRegistryVersions, !b.contains(s.registryVersion) { throw ValidationError.wrongBase(s.registryVersion) }
        let ids = Set(s.assets.map(\.id))
        for p in patches where !ids.contains(p.id) { throw ValidationError.unknownID(p.id) }
        for a in added ?? [] where ids.contains(a.id) { throw ValidationError.duplicateID(a.id) }
    }

    public func apply(to s: RegistrySnapshot) -> RegistrySnapshot {
        var out = s
        let byID = Dictionary(patches.map { ($0.id, $0) }, uniquingKeysWith: { _, b in b })
        out.assets = s.assets.map { a in
            guard let p = byID[a.id] else { return a }
            var a = a
            if let v = p.binanceSymbol { a.binanceSymbol = v.uppercased() }
            if let v = p.bybitSymbol { a.bybitSymbol = v.uppercased() }
            if let v = p.exchangeSymbols { a.exchangeSymbols.merge(v) { _, b in b } }
            if let v = p.contracts { a.contracts.merge(v) { _, b in b } }
            if let v = p.stablecoin { a.stablecoin = v }
            return a
        } + (added ?? [])
        return out
    }
}

/// Immutable, indexed registry. Build once; lookups are dictionary reads.
public final class AssetRegistry: Sendable {
    public let version: String
    public let overlayVersions: [String]
    public let assets: [RegistryAsset]          // market-cap rank order
    private let byID: [String: RegistryAsset]
    private let byCoinGecko: [String: RegistryAsset]
    private let bySymbol: [String: [RegistryAsset]]

    public init(snapshot: RegistrySnapshot, overlays: [RegistryOverlay] = []) {
        var s = snapshot, applied: [String] = []
        for o in overlays where (try? o.validate(against: s)) != nil { s = o.apply(to: s); applied.append(o.overlayVersion) }
        version = s.registryVersion
        overlayVersions = applied
        assets = s.assets.sorted { ($0.marketCapRank ?? .max, $0.id) < ($1.marketCapRank ?? .max, $1.id) }
        byID = Dictionary(assets.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        byCoinGecko = Dictionary(assets.compactMap { a in a.coingeckoId.map { ($0, a) } }, uniquingKeysWith: { a, _ in a })
        bySymbol = Dictionary(grouping: assets, by: \.symbol)
    }

    /// The bundled snapshot plus the curated overlay and any valid cached remote overlay.
    public static let shared: AssetRegistry = {
        var overlays = [RegistryOverlay.curated]
        if let cached = RegistryOverlayStore.default.cachedOverlay() { overlays.append(cached) }
        return AssetRegistry(snapshot: bundledSnapshot() ?? RegistrySnapshot(registryVersion: "missing", assets: []), overlays: overlays)
    }()

    public static func bundledSnapshot() -> RegistrySnapshot? {
        guard let url = Bundle.module.url(forResource: "CanonicalAssetRegistry", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(RegistrySnapshot.self, from: data)
    }

    public var count: Int { assets.count }
    public func entry(registryID id: String) -> RegistryAsset? { byID[id] }
    public func entry(coingeckoID id: String) -> RegistryAsset? { byCoinGecko[id] }
    public func entries(symbol: String) -> [RegistryAsset] { bySymbol[symbol.uppercased()] ?? [] }

    /// Registry record for a ledger asset: via its CoinGecko id (catalog overrides like
    /// `cg:telcoin` → `telcoin-2` included) or a `cmc:<n>` id. Never by ticker.
    public func entry(for asset: Asset) -> RegistryAsset? {
        if let cg = asset.coingeckoID, let e = byCoinGecko[cg] { return e }
        return entry(forID: asset.id)
    }

    public func entry(forID id: AssetID) -> RegistryAsset? {
        if id.hasPrefix("cmc:") { return byID["cmc-" + id.dropFirst(4)] }
        guard id.hasPrefix("cg:") else { return nil }
        let cg = AssetCatalog.known.first { $0.id == id }?.coingeckoID ?? String(id.dropFirst(3))
        return byCoinGecko[cg]
    }

    /// The ledger id an asset from this registry gets. Existing catalog ids win, so a registry
    /// pick and a typed symbol land on the same record.
    public func assetID(for e: RegistryAsset) -> AssetID {
        if let cg = e.coingeckoId {
            return AssetCatalog.known.first { $0.coingeckoID == cg }?.id ?? "cg:" + cg
        }
        return "cmc:" + e.id.replacingOccurrences(of: "cmc-", with: "")
    }

    /// A ledger `Asset` for a registry record (identity only; market mappings are looked up).
    public func asset(for e: RegistryAsset) -> Asset {
        Asset(id: assetID(for: e), symbol: e.symbol, name: e.name, coingeckoID: e.coingeckoId,
              binanceSymbol: MarketMappings.validBinance(e.binanceSymbol))
    }

    /// Local search: exact symbol, symbol prefix, name prefix, then substring / id matches;
    /// market-cap rank breaks ties. Works offline, never calls a provider.
    public func search(_ query: String, limit: Int = 8) -> [RegistryAsset] {
        let q = query.trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return [] }
        let u = q.uppercased(), l = q.lowercased()
        func score(_ a: RegistryAsset) -> Int? {
            let n = a.name.lowercased()
            if a.symbol == u || n == l { return 0 }      // exact ticker or name; rank breaks ties
            if a.symbol.hasPrefix(u) { return 1 }
            if n.hasPrefix(l) { return 2 }
            if a.coingeckoId?.lowercased() == l || a.id.lowercased() == l { return 2 }
            if l.count >= 3, n.contains(l) || (a.coingeckoId?.contains(l) ?? false) { return 3 }
            return nil
        }
        return assets.compactMap { a in score(a).map { (a, $0) } }
            .sorted { ($0.1, $0.0.marketCapRank ?? .max) < ($1.1, $1.0.marketCapRank ?? .max) }
            .prefix(limit).map(\.0)
    }
}
